### PR TITLE
Add support for HAProxy PROXY protocol

### PR DESCRIPTION
**Pull request by mikroskeem**
See:
- https://github.com/Steveice10/MCProtocolLib/issues/611
- https://github.com/GeyserMC/Geyser/pull/1688

### CODE REVIEW

**Comment by Steveice10** [comment]
Regarding clientAddress:
* Since it's only for proxy protocol support, I would prefer if it were stored in the flags along with the enable Boolean.
* Regardless, the constructor without it should not be deprecated, as users not using proxy support don't need it.

**Comment by mikroskeem** [comment]
Requested changes have been made.

**Comment by Steveice10** [comment]
Only comment I have left is the Deprecated on the constructor should be removed. Other than that, looks good to me.

I assume you've tested to make sure everything still works?

**Comment by mikroskeem** [comment]
> I assume you've tested to make sure everything still works?

I would've liked to run proper `mvn clean package` before merging and confirmed explicitly (because how maven can mess up with its caching sometimes); but yeah things worked out fine.

Thanks for merging it.

**Pull request merged**
