### PR TITLE
Update PacketProtocol, StreamNetInput, pom to 1.8

### PR DESCRIPTION
**Pull request by ipbeegle**
Added reverse mappings for outgoing packets (class->id) and added some missing InputStream methods to StreamNetInput.

Maven was complaining about dnsjava being Java 1.8, so I updated the pom to fix that.

There are a few syntax changes that can be made to bring the code more inline with 1.7/1.8 (e.g. using the Diamond Operator for the Maps in PacketProtocol), but I didn't include them in case the older style was your preference.

### CODE REVIEW

**Comment by Steveice10** [comment]
Two comments I have:
* In the first commit's changes, could you move the assignment out of the if statement? I'm guessing you put it there so the negative check would execute first, but honestly the negative check is actually probably unnecessary since negative IDs, if invalid, won't exist in the map anyway, so it can be removed.
* Could you add javadocs to the new methods in StreamNetInput? The other methods in there don't have them since they inherit from NetInput, but since those are specific to StreamNetInput they should be javadoc'd there.

**Comment by Steveice10** [comment]
Also, older style code is probably just a hold-over from when 1.7/1.8 were newer and less adopted, so you're free to update stuff to use diamond operators and the like if you wish.

**Comment by ipbeegle** [comment]
I've remove the negative check. I was going to break the registration check into a second if block, but this allows (although unlikely) registration of negative packet ids. I just converted StreamNetInput to extend FilterInputStream since it was made for this purpose and is what I should have used originally. I've also done the same with StreamNetOutput.

For the syntax changes, I've done them in the files affected by this pull request, but I'll have to look at the rest of the project another time.

**Comment by Steveice10** [comment]
Looks good, thanks.

**Pull request merged**
